2024-06-19 00:22:22 - logger - INFO - Start app
2024-06-19 00:45:24 - logger - INFO - Start app
2024-06-19 00:45:57 - logger - INFO - Start app
2024-06-19 00:46:10 - logger - INFO - Start app
2024-06-19 00:46:38 - logger - INFO - Start app
2024-06-19 00:46:59 - logger - INFO - Start app
2024-06-19 00:47:52 - logger - INFO - Start app
2024-06-19 00:48:24 - logger - INFO - Start app
2024-06-19 00:50:39 - logger - INFO - Start app
2024-06-19 00:50:39 - logger - ERROR - Произошла ошибка при запуске приложения
Traceback (most recent call last):
  File "D:\duplicateImages\main.py", line 11, in main
    window = MainWindow()
  File "D:\duplicateImages\GUI\main_window.py", line 52, in __init__
    button.setIconSize(Qt.QSize(24, 24))
AttributeError: type object 'Qt' has no attribute 'QSize'
2024-06-19 00:50:55 - logger - INFO - Start app
2024-06-19 00:50:55 - logger - ERROR - Произошла ошибка при запуске приложения
Traceback (most recent call last):
  File "D:\duplicateImages\main.py", line 11, in main
    window = MainWindow()
  File "D:\duplicateImages\GUI\main_window.py", line 52, in __init__
    button.setIconSize(Qt.QSize(24, 24))
AttributeError: type object 'Qt' has no attribute 'QSize'
2024-06-19 00:52:00 - logger - INFO - Start app
2024-06-19 00:52:00 - logger - ERROR - Произошла ошибка при запуске приложения
Traceback (most recent call last):
  File "D:\duplicateImages\main.py", line 11, in main
    window = MainWindow()
  File "D:\duplicateImages\GUI\main_window.py", line 11, in __init__
    self.main_widget.setStyleSheet("background-color: #f0f0f0;")
AttributeError: 'MainWindow' object has no attribute 'main_widget'
2024-06-19 00:52:10 - logger - INFO - Start app
2024-06-19 00:52:25 - logger - INFO - Start app
2024-06-19 00:53:21 - logger - INFO - Start app
2024-06-19 00:53:48 - logger - INFO - Start app
2024-06-19 00:54:44 - logger - INFO - Start app
2024-06-19 00:55:52 - logger - INFO - Start app
2024-06-19 00:56:08 - logger - INFO - Start app
2024-06-19 00:56:24 - logger - INFO - Start app
2024-06-19 00:59:40 - logger - INFO - Start app
2024-06-19 00:59:48 - logger - INFO - Start app
2024-06-19 01:01:22 - logger - INFO - Start app
2024-06-19 01:01:22 - logger - ERROR - Произошла ошибка при запуске приложения
Traceback (most recent call last):
  File "D:\duplicateImages\main.py", line 11, in main
    window = MainWindow()
  File "D:\duplicateImages\GUI\main_window.py", line 62, in __init__
    grey_strip.setLayout(grey_layout)
NameError: name 'grey_strip' is not defined
2024-06-19 01:01:48 - logger - INFO - Start app
2024-06-19 01:04:59 - logger - INFO - Start app
2024-06-19 01:06:48 - logger - INFO - Start app
2024-06-19 01:07:03 - logger - INFO - Start app
2024-06-19 01:10:00 - logger - INFO - Start app
2024-06-19 01:10:25 - logger - INFO - Start app
2024-06-19 01:11:29 - logger - INFO - Start app
2024-06-19 01:12:39 - logger - INFO - Start app
2024-06-19 01:14:54 - logger - INFO - Start app
2024-06-19 01:15:15 - logger - INFO - Start app
2024-06-19 01:15:29 - logger - INFO - Start app
2024-06-19 01:15:44 - logger - INFO - Start app
2024-06-19 01:15:53 - logger - INFO - Start app
2024-06-19 01:16:09 - logger - INFO - Start app
2024-06-19 01:16:22 - logger - INFO - Start app
2024-06-19 01:17:50 - logger - INFO - Start app
2024-06-19 01:18:16 - logger - INFO - Start app
2024-06-19 01:18:33 - logger - INFO - Start app
2024-06-19 01:18:59 - logger - INFO - Start app
2024-06-19 01:19:34 - logger - INFO - Start app
2024-06-19 01:21:56 - logger - INFO - Start app
2024-06-19 01:21:56 - logger - ERROR - Произошла ошибка при запуске приложения
Traceback (most recent call last):
  File "D:\duplicateImages\main.py", line 11, in main
    window = MainWindow()
  File "D:\duplicateImages\GUI\main_window.py", line 74, in __init__
    grey_strip.setLayout(grey_layout)
NameError: name 'grey_strip' is not defined
2024-06-19 01:22:18 - logger - INFO - Start app
2024-06-19 01:22:19 - logger - ERROR - Произошла ошибка при запуске приложения
Traceback (most recent call last):
  File "D:\duplicateImages\main.py", line 11, in main
    window = MainWindow()
  File "D:\duplicateImages\GUI\main_window.py", line 74, in __init__
    external_layout.setLayout(grey_layout)
AttributeError: 'QHBoxLayout' object has no attribute 'setLayout'
2024-06-19 01:22:38 - logger - INFO - Start app
2024-06-19 01:22:45 - logger - INFO - Start app
2024-06-19 01:22:51 - logger - INFO - Start app
2024-06-19 01:22:58 - logger - INFO - Start app
2024-06-19 01:23:08 - logger - INFO - Start app
2024-06-19 01:23:40 - logger - INFO - Start app
2024-06-19 01:26:43 - logger - INFO - Start app
2024-06-19 01:41:58 - logger - INFO - Start app
2024-06-19 01:42:18 - logger - INFO - Start app
2024-06-19 01:45:13 - logger - INFO - Start app
2024-06-19 01:45:21 - logger - INFO - Start app
2024-06-19 01:46:13 - logger - INFO - Start app
2024-06-19 01:46:35 - logger - INFO - Start app
2024-06-19 01:46:43 - logger - INFO - Start app
2024-06-19 01:46:56 - logger - INFO - Start app
2024-06-19 01:48:28 - logger - INFO - Start app
2024-06-19 01:49:31 - logger - INFO - Start app
2024-06-19 01:49:50 - logger - INFO - Start app
2024-06-19 01:50:00 - logger - INFO - Start app
2024-06-19 01:50:08 - logger - INFO - Start app
2024-06-19 01:50:16 - logger - INFO - Start app
2024-06-19 01:50:22 - logger - INFO - Start app
2024-06-19 01:50:28 - logger - INFO - Start app
2024-06-19 01:50:33 - logger - INFO - Start app
2024-06-19 01:50:38 - logger - INFO - Start app
2024-06-19 01:50:54 - logger - INFO - Start app
2024-06-19 01:51:06 - logger - INFO - Start app
2024-06-19 01:53:23 - logger - INFO - Start app
2024-06-19 01:53:42 - logger - INFO - Start app
2024-06-19 01:54:06 - logger - INFO - Start app
2024-06-19 01:54:18 - logger - INFO - Start app
2024-06-19 01:55:36 - logger - INFO - Start app
2024-06-19 01:55:49 - logger - INFO - Start app
2024-06-19 01:56:04 - logger - INFO - Start app
2024-06-19 01:56:14 - logger - INFO - Start app
2024-06-19 01:56:29 - logger - INFO - Start app
2024-06-19 01:56:43 - logger - INFO - Start app
2024-06-19 01:56:48 - logger - INFO - Start app
